# Generated by Django 4.2.7 on 2025-07-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
