# Generated by Django 4.2.7 on 2025-07-10 12:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual')], max_length=16, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal', models.ForeignKey(blank=True, help_text='Optional: Donor may or may not target a specific appeal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='appeals.appeal')),
                ('donor', models.ForeignKey(help_text='Must have role = Donor', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Wallet',
                'verbose_name_plural': 'System Wallets',
                'db_table': 'system_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'wallet_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'status', 'created_at'], name='donations_donor_i_6650d2_idx'),
        ),
    ]
