# Generated by Django 4.2.7 on 2025-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('mawalat_al_qurba', 'Mawalat al-Qurba'), ('general', 'General Donation'), ('appeal_specific', 'Appeal Specific')], default='mawalat_al_qurba', help_text='Type of donation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_type'], name='donations_donatio_bf7162_idx'),
        ),
    ]
