# Generated by Django 4.2.7 on 2025-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_donation_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_donor_i_6650d2_idx',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'created_at'], name='donations_donor_i_7a31e2_idx'),
        ),
    ]
