# Generated by Django 4.2.7 on 2025-07-10 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('house_rent', 'House Rent'), ('school_fee', 'School Fee'), ('medical', 'Medical'), ('utility_bills', 'Utility Bills'), ('debt', 'Debt'), ('business_support', 'Business Support'), ('death_support', 'Death Support'), ('other', 'Other')], max_length=32)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_monthly', models.BooleanField(default=False)),
                ('months_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_approved', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals_beneficiary', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
                'db_table': 'appeals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status', 'beneficiary', 'created_at'], name='appeals_categor_614381_idx')],
            },
        ),
    ]
