# Generated by Django 4.2.7 on 2025-07-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_donation_donations_donor_i_6650d2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='linked_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_appeals', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appeals', to=settings.AUTH_USER_MODEL),
        ),
    ]
