# Generated by Django 4.2.7 on 2025-07-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_alter_appeal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
