# Generated by Django 4.2.7 on 2025-07-10 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_syed',
            field=models.BooleanField(default=False, help_text='Only verified Sadaat can submit Mawaddah appeals', verbose_name='Verified Syed Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('shura', 'Shura Member'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='User Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Managed by system for incoming disbursements', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Wallet Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa')], max_length=20, null=True, verbose_name='Withdrawal Method'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
